{% set name = "up42-py" %}
{% set version = "0.28.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/up42-py-{{ version }}.tar.gz
  sha256: abbb940bbeb762550677a9e97446a7c9b405751908824aaf6a53e2d60a588242

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - branca
    - descartes
    - folium
    - geojson
    - geopandas
    - matplotlib-base
    - python >=3.7
    - rasterio
    - requests
    - requests-oauthlib
    - tenacity
    - tqdm
    - pystac-client

test:
  imports:
    - up42
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/up42/up42-py
  summary: Python SDK for UP42
  license: MIT
  license_file: LICENSE
  doc_url: https://sdk.up42.com
  dev_url: https://github.com/up42/up42-py

extra:
  recipe-maintainers:
    - andher1802
    - chrieke
