{% set name = "up42-py" %}
{% set version = "0.29.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/up42-py-{{ version }}.tar.gz
  sha256: c87ca92e7fb22202fc06cddaf372bc36e61bb4f0f5165d2a7205682b298dc939

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - branca
    - folium
    - geojson
    - geopandas
    - matplotlib-base
    - python >=3.7
    - rasterio
    - requests
    - requests-oauthlib
    - tenacity
    - tqdm
    - pystac-client
    - shapely
    - oauthlib
    - pandas
    - numpy

test:
  imports:
    - up42
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/up42/up42-py
  summary: Python SDK for UP42
  license: MIT
  license_file: LICENSE
  doc_url: https://sdk.up42.com
  dev_url: https://github.com/up42/up42-py

extra:
  recipe-maintainers:
    - andher1802
    - seedlit
