{% set name = "up42-py" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 47b31ed99a01bd6cd38b076b2e303e2cccf4f5b3ab264a0248d3c37bf5acd283

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  build:
    - pip
    - python >=3.9, <4
    - setuptools
    - wheel
  host:
    - pip
    - python {{ python_min }}
    - poetry
  run:
    - geojson ==3.1.0
    - python >={{ python_min }},<4
    - requests >=2.32.4, <2.33.0
    - tqdm ==4.66.0
    - tenacity ==8.4.1
    - pystac-client >=0.7.2, <0.8.0
    - urllib3 >=2.5.0, <2.6.0

test:
  imports:
    - up42
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/up42/up42-py
  summary: Python SDK for UP42
  license: MIT
  license_file: LICENSE
  doc_url: https://sdk.up42.com
  dev_url: https://github.com/up42/up42-py

extra:
  recipe-maintainers:
    - mohamed-aboshosha-up42
    - matheuspinheirosantos
    - abossart
    - janchrizz
    - jmigueldelgado
    - andher1802
