{% set name = "up42-py" %}
{% set version = "0.35.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b1dea95dc959240fe4d68562b36113da69f132447243f956678ad481e23e82b5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  build:
    - pip
    - python >=3.8, <3.12
    - setuptools
    - wheel
  host:
    - pip
    - python >=3.8, <3.12
    - poetry
  run:
    - branca
    - folium
    - geojson ==3.0.1
    - geopandas ==0.13.2
    - matplotlib-base
    - python >=3.8, <3.12
    - rasterio
    - requests ==2.31.0
    - requests-oauthlib
    - tenacity ==8.2.2
    - tqdm ==4.66.0
    - pystac-client ==0.7.2
    - shapely
    - oauthlib
    - pandas
    - numpy
    - pystac
    - poetry

test:
  imports:
    - up42
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/up42/up42-py
  summary: Python SDK for UP42
  license: MIT
  license_file: LICENSE
  doc_url: https://sdk.up42.com
  dev_url: https://github.com/up42/up42-py

extra:
  recipe-maintainers:
    - andher1802
    - seedlit
